Repository graasp/graasp-sdk, pull requests merged in 2023-04, with the labels that each got.

#126 chore: add auto-tag
  .github/workflows/auto-tag.yml
  .github/workflows/release-please.yml
Labels: chore

#127 fix: typo
  .github/workflows/release-please.yml
Labels: bug

#150 fix: add embedded link item settings
  src/services/items/interfaces/item.ts
Labels: bug

#143 feat: add etherpad service
  package.json
  src/declarations.ts
  src/services/etherpad/index.ts
  src/services/etherpad/interfaces/service.ts
  yarn.lock
Labels: feature

#158 fix: add lang prop in ItemSettings
  src/services/items/interfaces/item.ts
Labels: bug
