Repository graasp/graasp-sdk, pull requests merged in 2023-11, with the labels that each got.

#321 fix: add account context
  src/constants/context.ts
Labels: chore

#337 fix!: remove fastify and aws sdk
  package.json
  src/interfaces/graasp-error.ts
  src/services/file/index.ts
  src/services/file/interfaces/configuration.ts
  src/services/file/interfaces/fileService.ts
  src/services/websockets/ws-client.ts
  yarn.lock
Labels: chore, dependencies

#339 fix: add support for webp image format
  src/constants/mimeTypes.ts
Labels: chore

#345 Update the short link's payload from item to itemId
  src/interfaces/shortLink.ts
Labels: improvement

#351 feat: implement the appendPathToUrl to construct URLs correctly
  src/utils/index.ts
  src/utils/navigation.test.ts
  src/utils/navigation.ts
  src/utils/url.test.ts
  src/utils/url.ts
Labels: feature
