Repository graasp/graasp-sdk, pull requests merged in 2023-10, with the labels that each got.

#278 feat: move websocket client to sdk, always restart ws client
  src/frontend/index.ts
  src/frontend/ws-client.ts
Labels: feature

#286 feat(types): add `Optional<T, K>` utility type to make some properties of a type optional
  src/types.ts
Labels: feature

#289 feat: add new chatbot interface (graasp/graasp#641)
  src/interfaces/chat-bot.ts
  src/interfaces/index.ts
Labels: feature

#298 fix: remove `UnknownExtra`
  src/interfaces/extra.ts
  src/services/app/interfaces/extra.ts
  src/services/etherpad/interfaces/etherpad.ts
  src/services/file/interfaces/extra.ts
  src/services/h5p/interfaces/extra.ts
  tsconfig.json
Labels: chore, improvement

#252 fix: use `DiscriminatedItem` instead of `Item`
  src/constants/itemType.ts
  src/services/action/interfaces.ts
  src/services/app/interfaces/appAction.ts
  src/services/app/interfaces/appData.ts
  src/services/app/interfaces/appSetting.ts
  src/services/categories/types.ts
  src/services/chat/types.ts
  src/services/flag/types.ts
  src/services/invitation/types.ts
  src/services/item-like/types.ts
  src/services/item-login/types.ts
  src/services/item-memberships/interfaces/item-membership.ts
  src/services/item-published/types.ts
  src/services/item-recycled/types.ts
  src/services/item-tags/types.ts
  src/services/item-validation/types.ts
  src/services/members/interfaces/member.ts
  src/utils/extra.ts
Labels: bug :beetle:

#312 fix: convert `ItemType` to const
  src/constants/itemType.ts
  src/services/items/interfaces/item.ts
  src/services/search/types.ts
  src/utils/extra.ts
Labels: chore

#225 fix: remove member from itemLike
  src/services/item-like/types.ts
Labels: chore

#307 fix: remove qs dep
  package.json
  src/utils/navigation.ts
  yarn.lock
Labels: chore, dependencies
