Repository graasp/graasp-sdk, pull requests merged in 2023-03, with the labels that each got.

#90 feat: add mimetypes
  src/constants/index.ts
  src/constants/mimeTypes.ts
Labels: feature

#83 feat: add document flavor extra property
  src/interfaces/extra.ts
  src/services/h5p/interfaces/extra.ts
  src/services/h5p/interfaces/task-manager.ts
  src/services/items/interfaces/item.ts
  src/utils/extra.ts
Labels: feature

#95 feat: add enableSaveActions property
  src/services/items/interfaces/item.ts
  src/services/members/interfaces/member.ts
Labels: feature

#100 feat: add ThumbnailSize to exported constants
  src/frontend/index.ts
  src/frontend/ui.ts
Labels: chore

#93 feat: add building utilities for extra
  src/utils/extra.ts
Labels: chore

#98 feat: add websocket types
  src/declarations.ts
  src/services/index.ts
  src/services/websockets/api/client.ts
  src/services/websockets/api/index.ts
  src/services/websockets/api/message.ts
  src/services/websockets/api/server.ts
  src/services/websockets/errors.ts
  src/services/websockets/index.ts
  src/services/websockets/interfaces/request.ts
  src/services/websockets/interfaces/service.ts
Labels: feature

#108 fix: etherpad extra type
  src/services/items/interfaces/item.ts
Labels: bug
