Repository graasp/graasp-sdk, pull requests merged in 2024-08, with the labels that each got.

#610 chore(main): release 4.23.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#618 chore(main): release 4.24.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#621 chore(main): release 4.25.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#623 fix: remove extra.app.settings key in item
  src/item/appItem/appItem.factory.test.ts
  src/item/appItem/appItem.factory.ts
  src/item/appItem/appItem.ts
Labels: improvement

#624 chore(main): release 4.25.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#585 feat: add guest and account types
  src/action/action.ts
  src/action/factory.ts
  src/app/app.ts
  src/chat/chat.ts
  src/index.ts
  src/itemLogin/factory.ts
  src/itemLogin/itemLogin.ts
  src/itemMembership/factory.ts
  src/itemMembership/itemMembership.ts
  src/member/constants.ts
  src/member/factory.ts
  src/member/member.test.ts
  src/member/member.ts
Labels: feature

#628 chore(main): release 4.26.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
