Repository graasp/graasp-sdk, pull requests merged in 2024-11, with the labels that each got.

#688 feat: make own validation for password
  package.json
  src/member/password.ts
  src/validation/isPasswordStrong.test.ts
  src/validation/isPasswordStrong.ts
  src/validation/utils.test.ts
  src/validation/utils.ts
  yarn.lock
Labels: chore

#690 chore(main): release 4.34.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#695 chore(main): release 4.35.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#696 chore(main): release 5.0.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#697 chore(main): release 5.1.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#689 feat: add email validation
  src/index.ts
  src/validation/isByteLength.test.ts
  src/validation/isByteLength.ts
  src/validation/isEmail.test.ts
  src/validation/isEmail.ts
  src/validation/isFQDN.test.ts
  src/validation/isFQDN.ts
  src/validation/isIP.test.ts
  src/validation/isIP.ts
  src/validation/testUtils.ts
Labels: feature

#699 chore(main): release 5.2.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#701 fix: remove member property from member profile
  src/member/member.ts
Labels: bug :beetle:

#702 fix: strong password type
  src/member/password.ts
  src/validation/isPasswordStrong.ts
Labels: bug :beetle:

#703 chore(main): release 5.2.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#708 chore(main): release 5.3.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#710 fix: remove displayName
  .husky/commit-msg
  .husky/post-commit
  .husky/pre-commit
  .husky/pre-push
  src/item/baseItem.ts
  src/item/factory.test.ts
  src/item/factory.ts
Labels: chore

#711 chore(main): release 5.3.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending
