Repository graasp/graasp-sdk, pull requests merged in 2024-09, with the labels that each got.

#643 feat: add support for AAC, FLAC, OGG and m4a
  src/mimeTypes/mimeTypes.ts
Labels: feature

#635 chore: update config comments
  tsconfig.cjs.json
  tsconfig.esm.json
Labels: chore

#644 chore(main): release 4.27.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#658 chore(main): release 4.29.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#659 chore(main): release 4.29.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#664 chore(main): release 4.30.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#668 chore(main): release 4.31.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
