Repository graasp/graasp-sdk, pull requests merged in 2024-06, with the labels that each got.

#539 fix: allow path to be undefined in getIdsFromPath util
  .gitignore
  src/item/itemUtils.test.ts
  src/item/itemUtils.ts
Labels: chore, improvement

#549 fix: ensure empty array
  src/array/array.test.ts
Labels: chore

#553 chore(main): release 4.13.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#563 chore(main): release 4.14.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#559 build: improve package distribution
  build.config.ts
  package.json
  src/shortLink/shortLink.ts
  tsconfig.esm.json
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: build

#564 chore(main): release 4.14.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#566 feat: add alignment enum
  src/enums/alignment.ts
  src/index.ts
  src/item/baseItem.ts
  src/item/fileItem/fileItem.ts
  src/item/itemSettings.ts
Labels: feature

#567 chore(main): release 4.15.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#569 fix: remove ui-related functions
  src/enums/alignment.ts
Labels: chore
